# Generated by Django 5.1.3 on 2025-11-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyClean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255, verbose_name='视频id')),
                ('video_url', models.URLField(verbose_name='视频地址')),
                ('author', models.CharField(max_length=255, verbose_name='作者')),
                ('video_description', models.TextField(verbose_name='视频文案')),
                ('video_duration', models.CharField(max_length=55, verbose_name='视频时长')),
                ('damaku_count', models.IntegerField(verbose_name='弹幕数量')),
                ('favorites_count', models.IntegerField(verbose_name='收藏人数')),
                ('likes_count', models.IntegerField(verbose_name='点赞人数')),
                ('image_url', models.URLField(verbose_name='图片地址')),
                ('publish_timestamp', models.DateTimeField(verbose_name='发布时间')),
                ('comments_count', models.IntegerField(verbose_name='评论人数')),
                ('tags', models.CharField(max_length=255, verbose_name='标签')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('video_type', models.CharField(max_length=100, verbose_name='视频类型')),
                ('category', models.CharField(max_length=100, verbose_name='类别')),
            ],
            options={
                'verbose_name': '学习数据',
                'verbose_name_plural': '学习数据列表',
                'db_table': 'study_clean',
            },
        ),
    ]
