# Generated by Django 5.1.3 on 2025-11-26 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号码')),
                ('face', models.ImageField(default='avatars/default.jpg', upload_to='avatars/', verbose_name='头像')),
                ('info', models.TextField(blank=True, null=True, verbose_name='个性简介')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='邮箱')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
        ),
    ]
