# Generated by Django 5.1.3 on 2025-11-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_options_user_is_active_alter_user_addtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('fid', models.IntegerField()),
                ('realname', models.CharField(max_length=11)),
                ('conten', models.TextField()),
                ('ctime', models.DateTimeField(null=True)),
            ],
        ),
    ]
