# Generated by Django 5.1.3 on 2025-11-28 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.studyclean', verbose_name='收藏的视频')),
            ],
            options={
                'unique_together': {('user', 'video')},
            },
        ),
    ]
