# Generated by Django 5.1.3 on 2025-11-28 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='added',
            new_name='added_time',
        ),
    ]
