# Generated by Django 5.1.3 on 2025-11-28 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_added_wishlist_added_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='conten',
            new_name='content',
        ),
    ]
