# Generated by Django 5.1.3 on 2025-12-08 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rec',
            options={'verbose_name': '推荐记录', 'verbose_name_plural': '推荐记录'},
        ),
        migrations.AddField(
            model_name='rec',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='rec',
            table='myapp_rec',
        ),
    ]
