# Generated by Django 5.1.3 on 2025-12-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_rec_options_rec_created_at_alter_rec_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rec',
            table='myhome_rec',
        ),
    ]
