# Generated by Django 5.1.3 on 2025-12-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_rec_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rec',
            table='myapp_rec',
        ),
    ]
